server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pro05
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

itemImgLocation: C:/shop/item
uploadPath: file:///C:/shop/

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace